// FaceTrack AI — Export helpers (frontend-only mode).
// Dependency-free CSV/JSON download + a print-to-PDF view (uses the browser's
// native print dialog, so no jsPDF needed). columns: [{ key, label, format? }].

function triggerDownload(filename, content, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function cell(row, col) {
  const raw = col.format ? col.format(row[col.key], row) : row[col.key];
  return raw == null ? '' : String(raw);
}

export function exportToCsv(filename, rows, columns) {
  const head = columns.map((c) => `"${c.label.replace(/"/g, '""')}"`).join(',');
  const body = rows
    .map((r) => columns.map((c) => `"${cell(r, c).replace(/"/g, '""')}"`).join(','))
    .join('\n');
  triggerDownload(filename.endsWith('.csv') ? filename : `${filename}.csv`, `${head}\n${body}`, 'text/csv;charset=utf-8');
}

export function exportToJson(filename, data) {
  triggerDownload(
    filename.endsWith('.json') ? filename : `${filename}.json`,
    JSON.stringify(data, null, 2),
    'application/json'
  );
}

// Open a styled, print-ready window the user can "Save as PDF" from.
export function printReport({ title = 'FaceTrack AI Report', subtitle = '', columns = [], rows = [] }) {
  const win = window.open('', '_blank', 'width=900,height=700');
  if (!win) return;
  const thead = columns.map((c) => `<th>${c.label}</th>`).join('');
  const tbody = rows
    .map((r) => `<tr>${columns.map((c) => `<td>${cell(r, c)}</td>`).join('')}</tr>`)
    .join('');
  win.document.write(`<!doctype html><html><head><title>${title}</title>
    <style>
      *{font-family:-apple-system,Segoe UI,Roboto,sans-serif;}
      body{padding:32px;color:#0f172a;}
      h1{margin:0 0 4px;font-size:20px;}
      .sub{color:#64748b;margin:0 0 18px;font-size:13px;}
      table{width:100%;border-collapse:collapse;font-size:12px;}
      th,td{border:1px solid #e2e8f0;padding:7px 9px;text-align:left;}
      thead th{background:#0ea5e9;color:#fff;}
      tbody tr:nth-child(even){background:#f8fafc;}
      .foot{margin-top:18px;color:#94a3b8;font-size:11px;}
    </style></head><body>
    <h1>${title}</h1><p class="sub">${subtitle}</p>
    <table><thead><tr>${thead}</tr></thead><tbody>${tbody}</tbody></table>
    <p class="foot">Generated by FaceTrack AI (demo) · ${new Date().toLocaleString()}</p>
    <script>window.onload=function(){window.print();}<\/script>
    </body></html>`);
  win.document.close();
}
